FROM fde-control-plane:due-correction-20261007

COPY src/fde_control_plane/static/meeting_review.html /app/src/fde_control_plane/static/meeting_review.html
COPY src/fde_control_plane/static/meeting_review.css /app/src/fde_control_plane/static/meeting_review.css
COPY src/fde_control_plane/static/meeting_review.js /app/src/fde_control_plane/static/meeting_review.js
