const { chromium } = require('playwright');
const assert = require('node:assert/strict');

(async () => {
  const browser = await chromium.launch({headless: true, channel: process.env.FDE_BROWSER_CHANNEL || 'msedge'});
  const errors = [];
  const desktop = await browser.newContext({viewport: {width: 1440, height: 1000}});
  const page = await desktop.newPage();
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://127.0.0.1:8211/preview-login');
  await page.locator('.todo').nth(6).waitFor();
  assert.equal(await page.locator('.todo').count(), 7);
  await page.locator('.evidence').first().locator('summary').click();
  await page.screenshot({path: 'D:/Temp/fde-review-desktop.png'});
  await page.screenshot({path: 'D:/Temp/fde-review-desktop-full.png', fullPage: true});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  const mobile = await browser.newContext({viewport: {width: 390, height: 844}, isMobile: true, deviceScaleFactor: 1});
  const phone = await mobile.newPage();
  phone.on('pageerror', error => errors.push(error.message));
  await phone.goto('http://127.0.0.1:8211/preview-login');
  await phone.locator('.todo').nth(6).waitFor();
  await phone.screenshot({path: 'D:/Temp/fde-review-mobile.png'});
  await phone.screenshot({path: 'D:/Temp/fde-review-mobile-full.png', fullPage: true});
  assert.equal(await phone.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.equal(await phone.locator('img').evaluateAll(images => images.every(image => image.complete && image.naturalWidth > 0)), true);
  await page.locator('.assignee').first().selectOption('member-primary');
  await page.locator('.due-date').first().fill('2026-10-07');
  for (let i=1;i<7;i++) await page.locator('.keep').nth(i).uncheck();
  await page.locator('#save').click();
  await page.getByText('草稿已保存。', {exact: true}).waitFor();
  assert.equal(await page.locator('.badge.ready').count(), 1);
  assert.equal(await page.locator('.badge.closed').count(), 6);
  await page.locator('#reload').click();
  await page.waitForFunction(() => document.querySelectorAll('.badge.closed').length === 6 && !document.querySelector('#reload').disabled);
  await page.locator('#submit').click();
  await page.locator('#confirm-dialog button[value="confirm"]').click();
  await page.getByText('已提交，1 项操作待审批。 卡片已发送 0 项。', {exact: true}).waitFor();
  assert.equal(await page.locator('#actions').isVisible(), false);
  const detail = await page.evaluate(async () => {
    const index = await (await fetch('/api/meetings')).json();
    return (await fetch('/api/meetings/'+index.meetings[0].record_id)).json();
  });
  assert.equal(detail.task_status, 'WAITING_APPROVAL');
  assert.equal(detail.approvals.length, 1);
  await page.route('**/api/meetings', route => route.abort('connectionrefused'));
  await page.locator('#reload').click();
  await page.getByText('暂时无法连接服务，请稍后重新加载。', {exact: true}).waitFor();
  assert.equal(await page.locator('#reload').isEnabled(), true);
  await page.unroute('**/api/meetings');
  await page.route('**/api/meetings', () => {});
  await page.locator('#reload').click();
  await page.getByText('响应超时，请重新加载确认当前状态。', {exact: true}).waitFor({timeout: 20000});
  assert.equal(await page.locator('#reload').isEnabled(), true);
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({desktop: 'passed', mobile: 'passed', save_reload_submit: 'passed', network_failure_timeout: 'passed', page_errors: errors.length}));
  await browser.close();
})().catch(error => {console.error(error); process.exit(1);});
